### ISSUE TITLE
Items Not Allowed - Click to See Notes

### ISSUE THREAD

**Issue by Michael-Grisso** [Michael-Grisso/aware-dog-food#18]

**Comment by Michael-Grisso** [comment]
Quick List of things that will detract points from the other sections:

1. No backend
2. Nothing that involves NPM or Node, no "npm install," "npm init," or "npm start."   However, we can use a JS import from a CDN if available.
3. No local DBs - we can only use JS, cookies, local storage, or firebase.
4. No user registration/login
5. Cheating or Plagiarism - We can use docs, StackOverflow, etc., but cannot copy an entire project

**Comment by Oceanriderrr** [comment]
All good
